name: Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pytest

    - name: Create tests directory
      run: mkdir tests

    - name: Download test_urls.py
      run: |
        curl -o ./tests/test_urls.py https://raw.githubusercontent.com/FrankMaverick/dati-semantic-cookiecutter/main/tests/test_urls.py

    - name: Run tests
      run: pytest -s ./tests/
